version: '3.7'
services:
  fdlistener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fdlistener

    environment:
      - DEBUG=${DEBUG}
      - REMOTE_ADDRESS=${REMOTE_ADDRESS}

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: "10m" # 限制每个日志文件大小
        max-file: "7" # 保留最近日志文件天数

    restart: always
